//<auto-generated>
namespace $safeprojectname$.ViewModels
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;
    using System.Threading.Tasks;

    /// <summary>
    /// トップ画面の ViewModel のインタフェース
    /// </summary>
    public partial interface ITopPageViewModel
    {
        int Id { get; set; }
    }

    /// <summary>
    /// トップ画面の ViewModel
    /// </summary>
    [DataContract]
    public partial class TopPageViewModel : ViewModelBase, ITopPageViewModel
    {
        #region Id:ID プロパティ
        /// <summary>
        /// ID
        /// </summary>
        private int id; 

        /// <summary>
        /// ID の変更前の処理
        /// </summary>
        partial void OnIdChanging(int value);

        /// <summary>
        /// ID の変更後の処理
        /// </summary>
        partial void OnIdChanged();

        /// <summary>
        /// ID の取得および設定
        /// </summary>
        [DataMember(Name = "id")]
        public int Id
        {
            get
            {
                return this.id;
            }

            set
            {
                if (this.id != value)
                {
                    this.OnIdChanging(value);
                    this.SetProperty<int>(ref this.id, value);
                    this.OnIdChanged();
                }
            }
        }
        #endregion //Id:ID プロパティ

    }

}