//<auto-generated>
namespace $safeprojectname$.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Runtime.Serialization;
    using System.Text;
    using System.Threading.Tasks;
    using System.Xml.Serialization;

    /// <summary>
    /// アプリケーション設定情報 のインタフェース
    /// </summary>
    public partial interface IApplicationSettings
    {
    }

    /// <summary>
    /// アプリケーション設定情報
    /// </summary>
    [XmlRoot("app-settings")]
    public partial class ApplicationSettings : IApplicationSettings
    {
    }

}