//<auto-generated>
namespace $safeprojectname$.Views
{
    using $safeprojectname$.Presenters;

    /// <summary>
    /// Presenter を持つ基底ページクラスのインタフェース
    /// </summary>
    /// <typeparam name="TPresenter"></typeparam>
    public interface IView<TPresenter> where TPresenter : IPresenter
    {
        /// <summary>
        /// Presenter の Get アクセサ
        /// </summary>
        TPresenter Presenter { get; }
    }
}
