//<auto-generated>
namespace $safeprojectname$.ViewModels
{
    using System.Runtime.Serialization;
    using $safeprojectname$.Common;
    using $safeprojectname$.Framework;

    /// <summary>
    /// PageViewModel 基底クラス
    /// </summary>
    [DataContract]
    public class ViewModelBase : BindableBase, ICleanup
    {
        /// <summary>
        /// 初期化処理
        /// </summary>
        public virtual void Initialize()
        {
        }

        /// <summary>
        /// 終了処理
        /// </summary>
        public virtual void Discard()
        {
            this.Cleanup();
        }

        /// <summary>
        /// インスタンスを解放します
        /// </summary>
        public virtual void Cleanup()
        {
        }
    }
}
